# Generated by Django 3.1.1 on 2020-12-04 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heronews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news_post',
            new_name='NewsPost',
        ),
    ]
