# Generated by Django 3.1.1 on 2020-12-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='strength',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='weakness',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
