# Generated by Django 3.1.1 on 2020-10-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superhero',
            old_name='identity',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='name',
        ),
    ]
